In [53]:
# Importing Libraries
import numpy as np
import tensorflow_hub as hub
from sklearn.metrics.pairwise import cosine_similarity

In [54]:
#Loading the Dataset
embedding= hub.load ("https://tfhub.dev/google/Wiki-words-250/2")

In [55]:
# Embedding king, man, woman, queen
a = embedding (["king"])
b = embedding (["man"])
c = embedding (["woman"])
d = embedding (["queen"])

In [56]:
# Storing the result ofvector(king) − vector(man) + vector(woman)
X= a-b+c
print("king-man+woman:", [X])

king-man+woman: [<tf.Tensor: shape=(1, 250), dtype=float32, numpy=
array([[-0.12994584, -0.17411731,  0.08241335, -0.09460426, -0.02963368,
         0.00833852, -0.01580581, -0.07200217, -0.0374763 , -0.01857486,
         0.04575163, -0.06350955,  0.0310036 ,  0.04439414,  0.06356907,
        -0.02856771,  0.05558529,  0.07249814, -0.02398837,  0.0455301 ,
        -0.07038731,  0.00989324, -0.05211002, -0.02339969, -0.10386609,
        -0.00747646, -0.0174827 , -0.15109651, -0.16803886, -0.03159868,
        -0.04374632,  0.0941674 ,  0.05635576, -0.11544351, -0.01706913,
        -0.0181496 ,  0.05560432,  0.01284544, -0.09410097,  0.08030569,
        -0.13458134, -0.12798919, -0.14993384,  0.06665589,  0.07577673,
        -0.12577374, -0.06869593, -0.10468247, -0.01054525, -0.07139292,
        -0.00569897, -0.02220746, -0.11851092, -0.09434773,  0.06391967,
         0.04567089,  0.14339279, -0.13938236, -0.03750862,  0.03229091,
         0.07670465,  0.05507568, -0.01978571,  0.0488369

In [57]:
# Storing the result of vector(king) − vector(man) + vector(queen) to find similarity of woman
Y= b-a+d
print("man-king+queen:", [Y])

man-king+queen: [<tf.Tensor: shape=(1, 250), dtype=float32, numpy=
array([[ 0.01681516, -0.08521656, -0.06851303,  0.0595478 , -0.10875496,
         0.10709716,  0.03006158, -0.02443278, -0.01117055, -0.11209973,
         0.05852605,  0.07159583,  0.07165094,  0.14366794, -0.01810386,
        -0.15666823,  0.07434727,  0.05848619, -0.02905447, -0.02952485,
         0.10458523, -0.00647739,  0.04915919, -0.05695554, -0.0138592 ,
         0.0461482 ,  0.10628796,  0.13474749,  0.03000064,  0.19051257,
         0.12343374,  0.02059592,  0.12196557, -0.11266758, -0.07886181,
        -0.08491204, -0.03072942,  0.03749049,  0.11240648, -0.04657238,
         0.03493292, -0.1225394 , -0.04957216, -0.03854577,  0.11260201,
        -0.01066366, -0.19665536,  0.08780457, -0.08849054, -0.03091501,
         0.03170084,  0.03101998, -0.05169848,  0.125536  , -0.02303532,
        -0.02656888, -0.00692867, -0.05032928,  0.11097574,  0.02092209,
        -0.10292269, -0.05135739, -0.09984776,  0.0850872

In [58]:
#Calculating the Cosine Similarity between Vectors of Words.

print("Similarity between king-man+woman and queen:",cosine_similarity(X,d))
print("Similarity between man-king+queen and woman:",cosine_similarity(Y,c))
print("Similarity between man and woman:",cosine_similarity(b,c))
print("Similarity between king and queen:",cosine_similarity(a,d))
print("Similarity between man and king:",cosine_similarity(b,a))
print("Similarity between woman and queen:",cosine_similarity(c,d))

Similarity between king-man+woman and queen: [[0.763873]]
Similarity between man-king+queen and woman: [[0.83955884]]
Similarity between man and woman: [[0.8381338]]
Similarity between king and queen: [[0.71021986]]
Similarity between man and king: [[0.36127636]]
Similarity between woman and queen: [[0.5902161]]


In [59]:
# Embedding Paris, France, Italy, Rome
a1 = embedding (["Paris"])
b1 = embedding (["France"])
c1 = embedding (["Italy"])
d1 = embedding (["Rome"])

In [60]:
# Storing the result ofvector(Paris) − vector(France) + vector(Italy)
X1= a1-b1+c1
print("Paris-France+Italy:", [X1])

Paris-France+Italy: [<tf.Tensor: shape=(1, 250), dtype=float32, numpy=
array([[-7.06323236e-03,  1.06687166e-01,  7.31521240e-03,
         5.26041798e-02,  1.89695656e-02,  8.40932727e-02,
         8.83067027e-04,  1.10935658e-01, -5.20010255e-02,
        -1.41617298e-01, -5.03391251e-02, -6.35691136e-02,
        -7.17586428e-02, -8.52132309e-03,  1.04058161e-01,
        -5.06601781e-02, -3.47199142e-02,  1.35877831e-02,
        -4.24716696e-02,  9.08860378e-03,  5.71915954e-02,
        -2.70423815e-02, -3.47405560e-02, -2.06796005e-02,
        -1.00331597e-01, -2.99576633e-02,  4.90206629e-02,
         2.33950149e-02, -1.65568106e-02,  6.71938285e-02,
         1.33611009e-01,  3.93283181e-02,  9.12448168e-02,
        -4.95099053e-02, -2.55508367e-02,  2.51908898e-02,
        -4.23668697e-02,  1.20001487e-01,  6.35651350e-02,
        -3.00902147e-02, -5.18453941e-02,  4.50439677e-02,
         2.86682546e-02, -8.11181217e-03, -2.34579779e-02,
        -8.82764161e-02,  3.76700796e-02,  6

In [61]:
# Storing the result of vector(Italy) − vector(Paris) + vector(Rome) to find similarity of France
Y1= c1-a1+d1
print("France-Paris+Italy:", [Y1])


France-Paris+Italy: [<tf.Tensor: shape=(1, 250), dtype=float32, numpy=
array([[ 9.65829194e-03,  1.50402617e-02,  1.02494225e-01,
        -1.00866050e-01,  8.80958587e-02,  1.05187044e-01,
         6.10304996e-05,  2.96332166e-02, -5.84375039e-02,
        -1.01902559e-01, -1.64616495e-01,  5.78956306e-02,
        -9.26014036e-02, -4.21449170e-03,  6.10140562e-02,
        -5.25101498e-02, -7.38929734e-02, -7.87460618e-03,
         5.91115579e-02,  7.67147541e-02,  1.26453459e-01,
         1.92631781e-02, -5.01099937e-02,  4.42669168e-03,
        -1.19286478e-02, -1.57005414e-02,  3.93925980e-02,
        -3.14971022e-02,  1.62983984e-02,  1.34116039e-02,
         1.74449310e-01,  9.30660814e-02,  1.13316759e-01,
        -2.67461926e-01, -3.61998752e-03,  6.20473288e-02,
        -1.06010437e-01,  2.00535893e-01, -1.60224549e-02,
         8.48757476e-02, -6.62501752e-02,  7.14381933e-02,
        -3.81751265e-03, -7.64440447e-02,  1.40486538e-01,
        -5.22043556e-02,  2.32038066e-01, -1

In [62]:
#Calculating the Cosine Similarity between Vectors of Words.

print("Similarity between Paris-France+Italy and Rome:",cosine_similarity(X1,d1))
print("Similarity between France-Paris+Italy and Rome:",cosine_similarity(Y1,d1))
print("Similarity between France and Italy:",cosine_similarity(b1,c1))
print("Similarity between Paris and Rome:",cosine_similarity(a1,d1))
print("Similarity between France and Paris:",cosine_similarity(b1,a1))
print("Similarity between Italy and Rome:",cosine_similarity(c1,d1))

Similarity between Paris-France+Italy and Rome: [[0.7295018]]
Similarity between France-Paris+Italy and Rome: [[0.7537309]]
Similarity between France and Italy: [[0.6112312]]
Similarity between Paris and Rome: [[0.5107142]]
Similarity between France and Paris: [[0.74734336]]
Similarity between Italy and Rome: [[0.7058664]]


In [63]:
# Creating list of words similar to dog
dog_related_words = ['canine','doggy','pooch','hound','tyke','pup','puppy','cur','mongrel','mutt','watchdog','bitch','sheepdog','hunter','bandog','whelp']

In [64]:
# Embedding all the words in the list similar to dog
embedder = []
for i in range(len(dog_related_words)):
  embedder.append(embedding([dog_related_words[i]]))


In [65]:
# Embedding Dog word
dog_embedder = embedding(['dog'])

In [66]:
similarity = {}
for i in range(len(embedder)):
  similarity[dog_related_words[i]] = cosine_similarity(dog_embedder,embedder[i])

In [67]:
# Sorting the dictionary based on the similarity value in ascending
sorted_similarity = {}
sorted_values = sorted(similarity.values())
for i in sorted_values:
    for k in similarity.keys():
        if similarity[k] == i:
            sorted_similarity[k] = similarity[k]
            break

print(sorted_similarity)


{'bandog': array([[0.]], dtype=float32), 'watchdog': array([[0.07606272]], dtype=float32), 'cur': array([[0.3497349]], dtype=float32), 'whelp': array([[0.45355585]], dtype=float32), 'mutt': array([[0.49267846]], dtype=float32), 'bitch': array([[0.50176835]], dtype=float32), 'pooch': array([[0.51102823]], dtype=float32), 'hunter': array([[0.5172389]], dtype=float32), 'tyke': array([[0.55394626]], dtype=float32), 'canine': array([[0.6049171]], dtype=float32), 'doggy': array([[0.6388842]], dtype=float32), 'mongrel': array([[0.68380666]], dtype=float32), 'pup': array([[0.6987275]], dtype=float32), 'hound': array([[0.78350145]], dtype=float32), 'sheepdog': array([[0.78973323]], dtype=float32), 'puppy': array([[0.8488173]], dtype=float32)}


In [68]:
# Printing top 5 words closest to dog
length = len(list(sorted_similarity))
print(length)
key = list(sorted_similarity.keys())
for i in range(length):
  if i<(length-5):
    continue
  else:
    print("Word :", key[i])
    print("Cosine Similarity :", sorted_similarity[key[i]])  


16
Word : mongrel
Cosine Similarity : [[0.68380666]]
Word : pup
Cosine Similarity : [[0.6987275]]
Word : hound
Cosine Similarity : [[0.78350145]]
Word : sheepdog
Cosine Similarity : [[0.78973323]]
Word : puppy
Cosine Similarity : [[0.8488173]]
